server:
  port: 8080

spring:
  profiles:
    active: ${APP_PROFILE:test}
  jpa:
    open-in-view: false
  output:
    ansi:
      enabled: always

logging:
  level:
    com:
      sulimann: TRACE
      root: INFO
      org:
        springframework:
          web: DEBUG
        hibernate: INFO

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:myclientid}
      client-secret: ${CLIENT_SECRET:myclientsecret}

jwt:
  secret: ${JWT_SECRET:myjwtsecret}
  duration: ${JWT_DURATION:86400}

cors:
  origins: ${CORS_ORIGINS:https://easyadmin.com.br,http://localhost:3000,http://localhost:5173,}
